allow setting workspaces for autotiling
outfoxxed/hy3 pull request #31
Opened 2023-09-12 22:41 UTC by andresilva

Add a new configuration `autotile:workspaces` that allows passing a space/comma separated list of workspace ids where autotiling should be enabled (defaults to `all`).

2023-09-13 08:05 UTC, outfoxxed requested changes
Also run `clang-format -i src/*`.

It might also be good to have an except mode, where only workspaces that are not in the list are autotiled.

2023-09-13 08:05 UTC, outfoxxed commented on src/Hy3Layout.cpp
> +		static const auto at_workspaces = getAutotileWorkspaces();
This will make updating the config value completely ineffective. You should find another way to recalculate the value only when required.

2023-09-13 08:05 UTC, outfoxxed commented on src/Hy3Layout.cpp
> +	auto at_workspaces = HyprlandAPI::getConfigValue(PHANDLE, "plugin:hy3:autotile:workspaces")->strValue;
use `static const auto` here

2023-09-13 10:47 UTC, andresilva commented
I think I addressed all the comments and also added the except mode.

2023-09-13 10:48 UTC, andresilva commented on README.md
> +      workspaces.except = <bool> # default: false
Not really sure if this is the best name but couldn't come up with anything better.

2023-09-13 10:50 UTC, andresilva commented on src/Hy3Layout.cpp
> +		return !this->at_workspaces.empty() && !this->at_workspaces.contains(workspace_id);
If autotile is enabled, workspaces is set to `all` and except is enabled, then nothing gets autotiled. It would be stupid to configure it this way but I think it's consistent.

2023-09-13 21:24 UTC, JakeStanger commented on README.md
> +      workspaces.except = <bool> # default: false
I'd personally prefer something akin to  `blacklist` or `invese_mode`.

2023-09-14 07:51 UTC, outfoxxed commented on README.md
> +      workspaces.except = <bool> # default: false
Imo `workspaces = not:1,2,3` makes the most sense

2023-09-14 10:29 UTC, andresilva commented
I implemented the suggestion from @outfoxxed by allowing to prefix the definition with `not:`.

2023-09-21 11:10 UTC, andresilva commented
Pinging for another review.

2023-09-22 08:04 UTC, outfoxxed requested changes
Apart from the mentioned nitpicks it works as expected.

2023-09-22 10:01 UTC, andresilva commented on src/Hy3Layout.cpp
> +		this->updateAtWorkspaces();
I guess the proper place would be if Hyprland provided a hook for when the config is updated.

2023-09-22 10:01 UTC, andresilva commented
Updated.

2023-09-25 08:46 UTC, outfoxxed commented
I'll get to it soon

2023-09-30 06:15 UTC, outfoxxed commented
Sorry for the wait, LGTM

2023-09-30 06:18 UTC, merged