Fully implement `resizeactivewindow` dispatcher for tiled and floating windows
outfoxxed/hy3 pull request #60
Opened 2024-01-21 09:50 UTC by github-usr-name

### Overview
The `resizeactivewindow` implementation in v0.34.0 was incomplete and only allowed tiled windows to be grown, not shrunk.  It was possible to workaround this by changing focus to a sibling node and then growing _that_ node, but this is clunky and inefficient.  This PR provides the missing functionality so that the `resizeactivewindow` dispatcher works similarly to the `dwindle` layout and `i3`/`sway`.  It also implements `resizeactivewindow` for floating windows, using the same logic as the `master` layer.

### Trivia:
- Ignore `.vscode` directory and all log files
- Remove `gcc` warnings by
  - Adding `default` cases with explicit returns as required (shouldn't be triggered unless the enum parameter was invalid anyway)
  - Surround a code block reached via an unused label with a `#ifdef` and provide `cmake` option

### Technical changes:
- Add logic to determine the edge which should be moved [resized] based on current node position as well as requested delta
- Factor-out `Hy3Node` tree walk (which was repeated in several places in `Hy3Layout.cpp`) into `Hy3Node` member `findSibling`
- Factor-out `Hy3Node` resize logic into utility function in `Hy3Layout`, re-use for both inner- and outer- nodes
- Minor refactoring of `Hy3Layout::resizeActiveWindow` to use nested if blocks as guards instead of having multiple returns, which I find easier to comprehend when reading the code

2024-01-21 10:12 UTC, github-usr-name commented
This has had reasonable amount of adhoc testing with 3-deep nested groups of various types without any stability or display issues.  Valgrind doesn't report any memory leaks.  The "which edge should we move?" detection logic would benefit from improvement because the centre window in a 3x3 matrix always gets expanded as consequence of the somewhat naive algorithm ("Is there space available in the direction of the delta?  Great, let's move that edge then") always picking that edge.  Nevertheless, I think it's a big usability improvement.  I have a few thoughts about possibly adding either an additional dispatcher which would permit explicit specification of the edge to be resized, and/or adding `eRectCorner m_anchor` to `Hy3Node` (defaulting to CORNER_NONE with a semantic meaning of `auto`)

2024-01-22 02:08 UTC, outfoxxed requested changes
This appears to break resizing expanded nodes.

Before:

https://github.com/outfoxxed/hy3/assets/83010835/1b0f1f8d-d719-4602-a8f0-0ada780fc65d

After:
https://github.com/outfoxxed/hy3/assets/83010835/8c63b555-9d29-4c41-889b-82ec5abbb4fc

2024-01-22 02:08 UTC, outfoxxed commented on CHANGELOG.md
>  ## Upcoming
These should be in upcoming, which will be marked as `0.35.0` when it releases

2024-01-22 02:08 UTC, outfoxxed commented on CMakeLists.txt
> +option(HY3_ENABLE_UNUSED_BLOCKS "Enable the compilation of unused blocks" FALSE)
Just comment the blocks in question instead of adding the ifdef. Expand in general just needs a fair amount of work.

2024-01-22 02:08 UTC, outfoxxed commented on src/Hy3Layout.cpp
> +#endif
just comment this

2024-01-22 08:12 UTC, github-usr-name commented on CHANGELOG.md
>  ## Upcoming
Done

2024-01-22 08:12 UTC, github-usr-name commented on CMakeLists.txt
> +option(HY3_ENABLE_UNUSED_BLOCKS "Enable the compilation of unused blocks" FALSE)
Done

2024-01-22 08:12 UTC, github-usr-name commented on src/Hy3Layout.cpp
> +#endif
Done

2024-01-22 08:21 UTC, github-usr-name commented
Changelog updated & #ifdev removed - apologies, I don't know your versioning workflow, will bear that in mind for future.

Expanded node resize breakage - probably being thick, but I don't spot the difference between the two videos.  Can you please expand further on what the issue is [expected behaviour / actual behaviour etc.]?  Going to be AFK till the weekend though so not able to do anything that can't be handled with SSH (esp. testing :( )

2024-01-29 09:02 UTC, github-usr-name commented
Reworked, still in progress - expanded resize looks OK, but there are some bugs relating to [1] minimum window size (needs to be validated recursively, not just at the resize level) & [2] mouse-based resizing permitting windows to exceed node area

2024-02-07 08:53 UTC, github-usr-name commented
Any update on this please?  I have somewhat under 2,000 lines of `diff` against master now that I'd really like to get merged which provide a lot of additional/missing functionality & bug fixes e.g. integration of floating window focus logic

2024-02-07 11:59 UTC, merged

2024-02-07 11:59 UTC, outfoxxed commented
Sorry, the review request either didn't give me a notification or I didn't see it.