Multiple keyboard-based focus/resize improvements
outfoxxed/hy3 pull request #73
Opened 2024-02-18 00:39 UTC by github-usr-name

- Add `hy3:resizenode` dispatcher, which functions just like `resizeactivewindow` but applied to a whole node
- Consider floating windows when handling `hy3:movefocus`
- Consider other monitors when handling `hy3:movefocus` 
- Don't permit direction-based focusing of tiled windows which are completely obscured by a floating window

2024-02-18 01:53 UTC, outfoxxed commented
I'm not currently available to do any code review, but

- Consider floating windows when handling hy3:movefocus
- Don't permit direction-based focusing of tiled windows which are completely obscured by a floating window

If these are not configurable they mist be to merge the PR without breaking peoples' workflows.

2024-02-18 08:04 UTC, github-usr-name commented
Thank you, I'll add those - had considered this already but chose not to predicated on avoiding exploding optionitis, hadn't considered principle of least surprise though.  Proposal:

- Add configuration field `default_movefocus_layer` with values "samelayer", "floating", "tiled", "all" ("same" meaning "operate at the same layer as the focused window). Default: "samelayer"
- Add configuration field `focus_obscured_windows <bool>`.  Default: `false` if `default_movefocus_layer` is "all", otherwise true (i.e. existing behaviour)
- Add optional `layer` argument to `hy3:movefocus` Default: the value of the configuration field `default_movefocus_layer`

Rationale:

- Behaviour is easily controllable at global level
- Defaults should not be surprising
- Fine-grained control is available for people with complex setups e.g. modal keymaps for window management

Please confirm that you're happy with this approach, I'll start implementing now working on basis that you _are_ unless you say otherwise & obviously would prefer not to waste time if that proposal doesn't make sense to you.

2024-02-18 12:21 UTC, outfoxxed commented
Sounds good to me, except I don't see the point of "floating"/"tiled" for default_movefocus_layer. It makes sense for the layer argument to movefocus though.

2024-02-18 23:03 UTC, github-usr-name commented
Done - I'm going to need to handle the `hyprlang` config change though

2024-02-19 08:33 UTC, github-usr-name commented
Righto, that's ready for review please

2024-02-23 09:26 UTC, outfoxxed commented
Ah sorry, missed this again, I'll review it today

2024-02-23 09:27 UTC, github-usr-name commented
Cheers, much appreciated

23 Feb 2024 09:26:17 outfoxxed ***@***.***>:

> 
> Ah sorry, missed this again, I'll review it today
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/outfoxxed/hy3/pull/73#issuecomment-1960986260], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ADH2UZYAM7BFHX2O54VQMYLYVBODNAVCNFSM6AAAAABDNWPHPCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRQHE4DMMRWGA].
> You are receiving this because you authored the thread.
> [Tracking image][https://github.com/notifications/beacon/ADH2UZZSQNLLAAODMFNKSFLYVBODNA5CNFSM6AAAAABDNWPHPCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTU4JDJI.gif]
>

2024-02-23 09:32 UTC, outfoxxed commented
bump for likely missed edit since your email reply didn't include it

2024-02-23 21:17 UTC, github-usr-name commented
Git identity .... yep, a little bit of information leakage lol, thanks for pointing it out.  I'm aware of it, have dropped a lot of paranoia since initially creating a GitHub account :).

2024-02-24 10:38 UTC, outfoxxed requested changes
Have not tested functionality yet. May have more comments after that.

2024-02-24 12:07 UTC, github-usr-name commented on .gitignore
> +.env.*
They're used by VSCode to configure the local environment before running a task - I've moved into `.vscode` directory and reverted the gitignore change

2024-02-24 12:08 UTC, github-usr-name commented on src/BitFlag.hpp
> +#define BITFLAG
Updated

2024-02-24 12:09 UTC, github-usr-name commented on src/Hy3Layout.cpp
> +	};
_shudder_ yuck, fixed

2024-02-24 12:22 UTC, github-usr-name commented on CHANGELOG.md
> +- Implement keyboard-based movement for floating windows
Perhaps a documentation issue, or if not then I've really missed something! I was unable to find bindings that allow me to:

- Switch focus from a tiled window to a floating window in a particular direction
- Vice versa, ensuring that the `hy3` focus sequence is strictly adhered to
- Move floating windows on a pixel-basis (I've noticed that Hyprland seems to have implemented cardinal-point-base movement since v0.35, which was after I started this)

Achieving a seamless tiled-and-floating focus integration took quite a bit of work both to figure out a model and also to implement it, so I'll be very surprised if equivalent functionality is already present.

2024-02-24 12:29 UTC, outfoxxed commented on CHANGELOG.md
> +- Implement keyboard-based movement for floating windows
No not equivalent, it just picked a window on the same layer when you moved focus.

2024-02-24 12:31 UTC, github-usr-name commented on src/Hy3Layout.cpp
> +				} // in theory this would never happen
Done

2024-02-28 11:04 UTC, outfoxxed commented
Alright I gave it a test.
- Some of the nodes focused, especially in "all" mode are kind of odd. Basing the target node off the nearest window edges instead of the center would likely help this quite a lot. Not a blocker for merging though.
- Resizenode feels kind of bad to use and should have a way to deal with all sides and not just the bottom left. Also not going to block merging.
- Multi-node navigation is broken (select a node larger than one window and try to move)
Otherwise looks fine.

2024-03-02 13:21 UTC, merged

2024-03-05 09:43 UTC, outfoxxed commented
@github-usr-name I had to revert this due to it breaking tab navigation. Feel free to re-open after thats fixed.

2024-03-05 13:57 UTC, github-usr-name commented
Will do, thanks - what's the breakage please (basic repro)?

5 Mar 2024 09:43:56 outfoxxed ***@***.***>:

> 
> @github-usr-name[https://github.com/github-usr-name] I had to revert this due to it breaking tab navigation. Feel free to re-open after thats fixed.
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/outfoxxed/hy3/pull/73#issuecomment-1978344168], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ADH2UZ6A4KDALIIWIR6Y35LYWWHVVAVCNFSM6AAAAABDNWPHPCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZYGM2DIMJWHA].
> You are receiving this because you were mentioned.
> [Tracking image][https://github.com/notifications/beacon/ADH2UZ5LJ6XI5N4BIMWBJ5DYWWHVVA5CNFSM6AAAAABDNWPHPCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTV5MROQ.gif]
>

2024-03-05 14:44 UTC, outfoxxed commented
Try to use movefocus to change the current tab.

2024-03-18 19:25 UTC, aacebedo commented
@github-usr-name It was impossible to focus tabbed window. Do you plan to correct the bug? I was very interested by this functlionalities.

2024-03-18 19:39 UTC, github-usr-name commented
Yes, absolutely intend to fix the problem.  Unfortunately I'm extremely busy at work right now and also can't replicate the issue, so haven't had an opportunity to look at it.

18 Mar 2024 19:25:44 Alexandre Acebedo ***@***.***>:

> 
> @github-usr-name[https://github.com/github-usr-name] It was impossible to focus tabbed window. Do you plan to correct the bug? I was very interested by this functlionalities.
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/outfoxxed/hy3/pull/73#issuecomment-2004749668], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ADH2UZ4IOU7FNJ576UHAFODYY45TNAVCNFSM6AAAAABDNWPHPCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBUG42DSNRWHA].
> You are receiving this because you were mentioned.
> [Tracking image][https://github.com/notifications/beacon/ADH2UZ3R367FXMDF2Z3RNGTYY45TNA5CNFSM6AAAAABDNWPHPCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTXPYGWI.gif]
>

2024-03-23 10:34 UTC, github-usr-name commented
Finally had a change to look.  Despite seeing video of the issue I'm completely unable to replicate it.  @aacebedo / @outfoxxed , it would be extremely helpful if you could please:

- Provide a complete copy of your `hyprland.conf` (redacted as needed)
- Confirm that you still observe the problem if you use my config (attached)

My code is on branch `feature/focus-by-keyboard` at https://github.com/github-usr-name/hy3/ - I don't want to reopen the PR until I've fixed the issue.

[My hyprland.conf](https://github.com/outfoxxed/hy3/files/14731183/hyprland.conf.txt)
[Noddy test script](https://github.com/outfoxxed/hy3/files/14731182/run-test.txt)

https://github.com/outfoxxed/hy3/assets/13609575/92111698-93db-4484-9318-70ea31042dc3

2024-04-04 06:03 UTC, outfoxxed commented
@github-usr-name apologies, took me a while to get to this. anyway it's still reproducible for me.

<details><summary>Stripped down config used below</summary>

```conf
plugin = /home/admin/programming/outfoxxed/hyprland/hy3/build/libhy3.so

general {
    layout = hy3
}

debug {
    enable_stdout_logs = true
}

monitor = , preferred, auto, 1

$mod = ALT

bind = $mod+SHIFT, m, exit

bind = $mod, return, exec, alacritty
bind = $mod+SHIFT, q, hy3:killactive

bind = $mod, d, hy3:makegroup, h
bind = $mod, s, hy3:makegroup, v
bind = $mod, z, hy3:makegroup, tab
bind = $mod, a, hy3:changefocus, raise
bind = $mod+SHIFT, a, hy3:changefocus, lower

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
bindn = , mouse:272, hy3:focustab, mouse
bindn = , mouse_down, hy3:focustab, l, require_hovered
bindn = , mouse_up, hy3:focustab, r, require_hovered

bind = $mod, h, hy3:movefocus, l
bind = $mod, j, hy3:movefocus, d
bind = $mod, k, hy3:movefocus, u
bind = $mod, l, hy3:movefocus, r
bind = $mod, left, hy3:movefocus, l
bind = $mod, down, hy3:movefocus, d
bind = $mod, up, hy3:movefocus, u
bind = $mod, right, hy3:movefocus, r

bind = $mod+CONTROL, h, hy3:movefocus, l, visible
bind = $mod+CONTROL, j, hy3:movefocus, d, visible
bind = $mod+CONTROL, k, hy3:movefocus, u, visible
bind = $mod+CONTROL, l, hy3:movefocus, r, visible
bind = $mod+CONTROL, left, hy3:movefocus, l, visible
bind = $mod+CONTROL, down, hy3:movefocus, d, visible
bind = $mod+CONTROL, up, hy3:movefocus, u, visible
bind = $mod+CONTROL, right, hy3:movefocus, r, visible

bind = $mod+SHIFT, h, hy3:movewindow, l, once
bind = $mod+SHIFT, j, hy3:movewindow, d, once
bind = $mod+SHIFT, k, hy3:movewindow, u, once
bind = $mod+SHIFT, l, hy3:movewindow, r, once
bind = $mod+SHIFT, left, hy3:movewindow, l, once
bind = $mod+SHIFT, down, hy3:movewindow, d, once
bind = $mod+SHIFT, up, hy3:movewindow, u, once
bind = $mod+SHIFT, right, hy3:movewindow, r, once

bind = $mod+CONTROL+SHIFT, h, hy3:movewindow, l, once, visible
bind = $mod+CONTROL+SHIFT, j, hy3:movewindow, d, once, visible
bind = $mod+CONTROL+SHIFT, k, hy3:movewindow, u, once, visible
bind = $mod+CONTROL+SHIFT, l, hy3:movewindow, r, once, visible
bind = $mod+CONTROL+SHIFT, left, hy3:movewindow, l, once, visible
bind = $mod+CONTROL+SHIFT, down, hy3:movewindow, d, once, visible
bind = $mod+CONTROL+SHIFT, up, hy3:movewindow, u, once, visible
bind = $mod+CONTROL+SHIFT, right, hy3:movewindow, r, once, visible
```
</details>

With this config you can observe that `hy3:movefocus, [l|d|u|r]` do not move between tabs, with or without `visible`.

https://github.com/outfoxxed/hy3/assets/83010835/9866c536-19cf-4f2a-87c1-2901c51c6ab8

2024-04-04 07:20 UTC, github-usr-name commented
And yet, with minimal config changes (just plugin path & terminal) I have totally different results!!

OK, in the interests of eliminating things, then I am going to install alacritty; can you please supply your config on the tiniest little possible outside chance that it's something like an OSC sequence?  Assuming that that doesn't show the problem then I'll prepare a branch with "insane logging" later on and ask if you could please supply the log output from that.

[test.webm](https://github.com/outfoxxed/hy3/assets/13609575/2fc7e040-4155-48e6-992e-c0d2ab0d6f40)

[test.log](https://github.com/outfoxxed/hy3/files/14862702/test.log)

2024-04-09 18:29 UTC, postsolar commented
@github-usr-name

I think there's a regression on this branch introduced by some recent Hyprland changes. I think it's since 0.38 or so, before that I've been using your branch just fine. When I use `hy3:movefocus` on a floating window Hyprland freezes and eventually crashes. I get this with a pretty much the default config. Did you experience this too recently?

2024-04-09 20:56 UTC, github-usr-name commented
Haven't seen that one, but I've only just upgraded my box & not really used it enough to say.  It'll be the weekend at the earliest before I can look, am away from home this week.

I have noticed sigsegv's on shutdown, coming from the CWorkspace destructor, coming from TabGroup dtor - looks like some sort of double-free type issue perhaps because 'this' had a value of 0x0.  Bit of a pain, I like the workspace pointer changes though.

9 Apr 2024 19:30:22 postsolar ***@***.***>:

> 
> @github-usr-name[https://github.com/github-usr-name]
> 
> I think there's a regression on this branch introduced by some recent Hyprland changes. I think it's since 0.38 or so, before that I've been using your branch just fine. When I use *hy3:movefocus* on a floating window Hyprland freezes and eventually crashes. I get this with a pretty much the default config. Did you experience this too recently?
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/outfoxxed/hy3/pull/73#issuecomment-2045838428], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ADH2UZ6QYVARAM76WIPFEQDY4QXTXAVCNFSM6AAAAABDNWPHPCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBVHAZTQNBSHA].
> You are receiving this because you were mentioned.
> [Tracking image][https://github.com/notifications/beacon/ADH2UZ3JVNQRZX4K3YKB4SLY4QXTXA5CNFSM6AAAAABDNWPHPCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTZ6ECFY.gif]
>

2024-04-11 05:23 UTC, postsolar commented
I noticed I'm getting the same freeze+crash if I do:
1. Open two windows, expand one of the windows with `hy3:expand expand`
2. Try to use `hy3:movefocus` in the direction where the other window was

I checked and it doesn't happen on base hy3.

2024-04-11 06:06 UTC, github-usr-name commented
Thank you, I appreciate the reproduction information.  Will have a look over the weekend.

11 Apr 2024 06:23:43 postsolar ***@***.***>:

> 
> I noticed I'm getting the same freeze+crash if I do:
> 
> 1. Open two windows, expand one of the windows with *hy3:expand expand*
> 2. Try to use *hy3:movefocus* in the direction where the other window was
> 
> I checked and it doesn't happen on base hy3.
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/outfoxxed/hy3/pull/73#issuecomment-2048947402], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ADH2UZ4PJ5OXRSTGZTMGHXDY4YM5XAVCNFSM6AAAAABDNWPHPCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBYHE2DONBQGI].
> You are receiving this because you were mentioned.
> [Tracking image][https://github.com/notifications/beacon/ADH2UZYPIZOPOZS4TT2GYY3Y4YM5XA5CNFSM6AAAAABDNWPHPCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTT2EB2MU.gif]
>

2024-04-20 00:08 UTC, postsolar commented
@github-usr-name sorry I didn't notice this message — although I did update and was using the new version without knowing this issue is fixed :D Thank you very much!